/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * Copyright (c) 2026, Asymm Systems (Pvt) Ltd.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

import java.security.Key;
import java.security.KeyFactory;
import java.security.PrivateKey;
import java.security.Provider;
import java.security.PublicKey;
import java.security.spec.DSAPrivateKeySpec;
import java.security.spec.DSAPublicKeySpec;
import java.security.spec.KeySpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.util.Arrays;
import java.util.Base64;

/*
 * @test
 * @summary Test the DSA KeyFactory of the SunPKCS11 provider, covering key
 *          translation, key generation from encoded specs, and the encoding
 *          of token-resident DSA keys
 * @library /test/lib ..
 * @modules jdk.crypto.cryptoki
 * @run main/othervm TestKeyFactory
 */
public class TestKeyFactory extends PKCS11Test {

    /*
     * A fixed 2048-bit DSA key pair, so the encodings this test compares are
     * reproducible from run to run. Generated by the SUN provider.
     */
    private static final String PUBLIC_X509 =
        "MIIDQjCCAjUGByqGSM44BAEwggIoAoIBAQCPeTXZuarpv6vtiHrPSVG28y7FnjuvNxjo6sSWHz79" +
        "NgbnQ1GpxBgzObgJ58KuHFObp0dbhdARrbi0eYd1SYRpXKwOjxSzNggooi/6JxEKPWKpk0U0CaD+" +
        "aWxGWPhL3SCBnDcJoBBXsZWtzQAjPbpUhLYpH51kjviDRIZ3l5zsBLQ0pqwudemYXeI9sCkvwRGM" +
        "n/qdgYHnM423krcw17njSVkvaAmYchU5Feo9a4tGU8YzRY+AOzKkwuDycpAlbk4/ijsIOKHEUOTh" +
        "jBopo33fXqFD3ktm/wSQPtXPFiPhWNSHxgjpfyEc2B3KI8tuOAdl+CLjQr5ITAV2OTlgHNZnAh0A" +
        "uvaWpoV499/e5/pnyXfHhe8ysjO65YDAvNVpXQKCAQAWplxYIEhQcE51AqOXVwQNNNo6NHjBVNTk" +
        "pcAtJC7gT5bmHkvQkEq9rI837rHgnzGC0jyQQ8tkL4gAQWDt+coJsyB2p5wypifyRz6Rh5uixOdE" +
        "vSCBVEy1W4AsNo0fqD7UielOD6BojjJCilx4xHjGjQUntxyaOrsLC+EsRGiWOefTznTbEBplqiuH" +
        "9kxoJts+xy9LVZmDS7TtsC98kOmkltOlXVNb6/xF1PYZ9j897buHOSXC8iTgdzEpbaiH7B5HSPh+" +
        "+1/et1SEMWsiMt7lU92vAhErDR8C2jCXMiT+J67ai51LKSLZuovjntnhA6Y8UoELxoi34u1DFuHv" +
        "F9veA4IBBQACggEAG9+htWktNPpC7CueGCbDNhdYgX+VW/CZ7iNB/ttASVW+Bwy6IwO2vzxxZ2CP" +
        "u34YoQCucBKv3xh1SXr7ZJ+XqQOANAwGorg+PERG90q2GnqodWal1T3nvVp89af27OGClw16XdmM" +
        "k49/K8mECpzJ6owZUXQ4nlsMsOLoRwOxv6droWTUJR+lUedXxu4fsyQOVOr1ZWURycyduAcJ1hgs" +
        "T7BUwBmO8IvOn9/HLMsf4srDuO/itIA3e7j3FDSjHc3khbom9POkPVLCdq2dEdcE1IVabWMGDias" +
        "OVR2TkH+sLak1nFGrptMUkPcqWaxsPdSaWxP73D2ubHUpuqkFpYIEg==";

    private static final String PRIVATE_PKCS8 =
        "MIICXAIBADCCAjUGByqGSM44BAEwggIoAoIBAQCPeTXZuarpv6vtiHrPSVG28y7FnjuvNxjo6sSW" +
        "Hz79NgbnQ1GpxBgzObgJ58KuHFObp0dbhdARrbi0eYd1SYRpXKwOjxSzNggooi/6JxEKPWKpk0U0" +
        "CaD+aWxGWPhL3SCBnDcJoBBXsZWtzQAjPbpUhLYpH51kjviDRIZ3l5zsBLQ0pqwudemYXeI9sCkv" +
        "wRGMn/qdgYHnM423krcw17njSVkvaAmYchU5Feo9a4tGU8YzRY+AOzKkwuDycpAlbk4/ijsIOKHE" +
        "UOThjBopo33fXqFD3ktm/wSQPtXPFiPhWNSHxgjpfyEc2B3KI8tuOAdl+CLjQr5ITAV2OTlgHNZn" +
        "Ah0AuvaWpoV499/e5/pnyXfHhe8ysjO65YDAvNVpXQKCAQAWplxYIEhQcE51AqOXVwQNNNo6NHjB" +
        "VNTkpcAtJC7gT5bmHkvQkEq9rI837rHgnzGC0jyQQ8tkL4gAQWDt+coJsyB2p5wypifyRz6Rh5ui" +
        "xOdEvSCBVEy1W4AsNo0fqD7UielOD6BojjJCilx4xHjGjQUntxyaOrsLC+EsRGiWOefTznTbEBpl" +
        "qiuH9kxoJts+xy9LVZmDS7TtsC98kOmkltOlXVNb6/xF1PYZ9j897buHOSXC8iTgdzEpbaiH7B5H" +
        "SPh++1/et1SEMWsiMt7lU92vAhErDR8C2jCXMiT+J67ai51LKSLZuovjntnhA6Y8UoELxoi34u1D" +
        "FuHvF9veBB4CHHzpJIwzsvNMOvYkfg4VvXtT06z5uKZcxKfQG4w=";

    /*
     * A public key that is neither a P11 key nor a DSAPublicKey, carrying only
     * an X.509 encoding. Translating it exercises the X.509 branch of
     * P11DSAKeyFactory.implTranslatePublicKey.
     */
    private static PublicKey encodingOnlyPublic(byte[] encoded) {
        return new PublicKey() {
            @Override
            public String getAlgorithm() {
                return "DSA";
            }
            @Override
            public String getFormat() {
                return "X.509";
            }
            @Override
            public byte[] getEncoded() {
                return encoded.clone();
            }
        };
    }

    /*
     * The PKCS#8 counterpart, for the branch of
     * P11DSAKeyFactory.implTranslatePrivateKey.
     */
    private static PrivateKey encodingOnlyPrivate(byte[] encoded) {
        return new PrivateKey() {
            @Override
            public String getAlgorithm() {
                return "DSA";
            }
            @Override
            public String getFormat() {
                return "PKCS#8";
            }
            @Override
            public byte[] getEncoded() {
                return encoded.clone();
            }
        };
    }

    private static void testKey(Key key1, Key key2) throws Exception {
        if (!key2.getAlgorithm().equals("DSA")) {
            throw new Exception("Algorithm not DSA");
        }
        if (key1 instanceof PublicKey) {
            if (!key2.getFormat().equals("X.509")) {
                throw new Exception("Format not X.509");
            }
        } else if (key1 instanceof PrivateKey) {
            if (!key2.getFormat().equals("PKCS#8")) {
                throw new Exception("Format not PKCS#8");
            }
        }
        if (!key1.equals(key2)) {
            throw new Exception("Keys not equal");
        }
        if (key1.getFormat().equals(key2.getFormat())
                && !Arrays.equals(key1.getEncoded(), key2.getEncoded())) {
            throw new Exception("Encodings not equal");
        }
    }

    private static void testPublic(KeyFactory kf, PublicKey key)
            throws Exception {
        System.out.println("Testing public key " + key.getClass().getName());
        PublicKey key2 = (PublicKey) kf.translateKey(key);
        KeySpec dsaSpec = kf.getKeySpec(key, DSAPublicKeySpec.class);
        PublicKey key3 = kf.generatePublic(dsaSpec);
        KeySpec x509Spec = kf.getKeySpec(key, X509EncodedKeySpec.class);
        PublicKey key4 = kf.generatePublic(x509Spec);
        testKey(key, key);
        testKey(key, key2);
        testKey(key, key3);
        testKey(key, key4);

        KeySpec x509Spec2 = new X509EncodedKeySpec(key.getEncoded());
        PublicKey key5 = kf.generatePublic(x509Spec2);
        testKey(key, key5);
    }

    private static void testPrivate(KeyFactory kf, PrivateKey key)
            throws Exception {
        System.out.println("Testing private key " + key.getClass().getName());
        PrivateKey key2 = (PrivateKey) kf.translateKey(key);
        KeySpec dsaSpec = kf.getKeySpec(key, DSAPrivateKeySpec.class);
        PrivateKey key3 = kf.generatePrivate(dsaSpec);
        KeySpec pkcs8Spec = kf.getKeySpec(key, PKCS8EncodedKeySpec.class);
        PrivateKey key4 = kf.generatePrivate(pkcs8Spec);
        testKey(key, key);
        testKey(key, key2);
        testKey(key, key3);
        testKey(key, key4);

        KeySpec pkcs8Spec2 = new PKCS8EncodedKeySpec(key.getEncoded());
        PrivateKey key5 = kf.generatePrivate(pkcs8Spec2);
        testKey(key, key5);
    }

    public static void main(String[] args) throws Exception {
        main(new TestKeyFactory(), args);
    }

    @Override
    public void main(Provider p) throws Exception {
        byte[] pubEncoded = Base64.getDecoder().decode(PUBLIC_X509);
        byte[] privEncoded = Base64.getDecoder().decode(PRIVATE_PKCS8);

        KeyFactory kf = KeyFactory.getInstance("DSA", p);

        // A key that carries an encoding and nothing else. This is the only
        // route into the X.509 and PKCS#8 branches of
        // implTranslatePublicKey / implTranslatePrivateKey, which is where
        // the SunJCE-owned key classes used to be constructed by name.
        PublicKey rawPub = encodingOnlyPublic(pubEncoded);
        PrivateKey rawPriv = encodingOnlyPrivate(privEncoded);

        PublicKey tokenPub = (PublicKey) kf.translateKey(rawPub);
        if (!Arrays.equals(pubEncoded, tokenPub.getEncoded())) {
            throw new Exception("Translated public key changed the encoding");
        }
        PrivateKey tokenPriv = (PrivateKey) kf.translateKey(rawPriv);
        if (!Arrays.equals(privEncoded, tokenPriv.getEncoded())) {
            throw new Exception("Translated private key changed the encoding");
        }

        // engineGeneratePublic / engineGeneratePrivate from an encoded spec.
        PublicKey genPub = (PublicKey) kf.generatePublic(
                new X509EncodedKeySpec(pubEncoded));
        if (!Arrays.equals(pubEncoded, genPub.getEncoded())) {
            throw new Exception("Generated public key changed the encoding");
        }
        PrivateKey genPriv = (PrivateKey) kf.generatePrivate(
                new PKCS8EncodedKeySpec(privEncoded));
        if (!Arrays.equals(privEncoded, genPriv.getEncoded())) {
            throw new Exception("Generated private key changed the encoding");
        }

        // Full round trip on the token-resident keys. getEncoded() here runs
        // P11Key.P11DSAPublicKey.getEncodedInternal and its private
        // counterpart, which build the encoding through a KeyFactory.
        testPublic(kf, tokenPub);
        testPrivate(kf, tokenPriv);

        System.out.println("All tests passed");
    }
}
